stages:
  - test
playwrightTests:
  stage: test
  image: mcr.microsoft.com/playwright:latest
  # parallel: 5
  script:
    - npm ci
    - npx playwright test --grep-invert @api
  artifacts:
    paths: #assuming deafult playwright artifacts paths 
      - ./playwright-report/
    when: always
    expire_in: 4 days  #artifacts will purged after 4 days of test run
